// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Music.EntityFramework;

#nullable disable

namespace Music.EntityFramework.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20250102041128_init9")]
    partial class init9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Music.Entity.Album", b =>
                {
                    b.Property<Guid>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SingerID")
                        .HasColumnType("TEXT");

                    b.HasKey("AlbumID");

                    b.HasIndex("AlbumID")
                        .IsUnique();

                    b.HasIndex("SingerID");

                    b.ToTable("albums");
                });

            modelBuilder.Entity("Music.Entity.Musicc", b =>
                {
                    b.Property<Guid>("MusicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlbumID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Composer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lyricist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MusicID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("MusicID")
                        .IsUnique();

                    b.ToTable("musiccs");
                });

            modelBuilder.Entity("Music.Entity.Singer", b =>
                {
                    b.Property<Guid>("SingerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DebutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SingerID");

                    b.HasIndex("SingerID")
                        .IsUnique();

                    b.ToTable("singers");
                });

            modelBuilder.Entity("Music.Entity.Song", b =>
                {
                    b.Property<Guid>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Composer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lyricist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MusicID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SongTableID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SongID");

                    b.HasIndex("MusicID")
                        .IsUnique();

                    b.HasIndex("SongID")
                        .IsUnique();

                    b.HasIndex("SongTableID");

                    b.ToTable("songs");
                });

            modelBuilder.Entity("Music.Entity.SongTable", b =>
                {
                    b.Property<Guid>("SongTableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsPublic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("SongTableID");

                    b.HasIndex("SongTableID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("songTables");
                });

            modelBuilder.Entity("Music.Entity.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Music.Entity.Album", b =>
                {
                    b.HasOne("Music.Entity.Singer", "singer")
                        .WithMany("albums")
                        .HasForeignKey("SingerID");

                    b.Navigation("singer");
                });

            modelBuilder.Entity("Music.Entity.Musicc", b =>
                {
                    b.HasOne("Music.Entity.Album", "album")
                        .WithMany("musics")
                        .HasForeignKey("AlbumID");

                    b.Navigation("album");
                });

            modelBuilder.Entity("Music.Entity.Song", b =>
                {
                    b.HasOne("Music.Entity.Musicc", "music")
                        .WithOne("song")
                        .HasForeignKey("Music.Entity.Song", "MusicID");

                    b.HasOne("Music.Entity.SongTable", "songTable")
                        .WithMany("songs")
                        .HasForeignKey("SongTableID");

                    b.Navigation("music");

                    b.Navigation("songTable");
                });

            modelBuilder.Entity("Music.Entity.SongTable", b =>
                {
                    b.HasOne("Music.Entity.User", "user")
                        .WithMany("songTables")
                        .HasForeignKey("UserID");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Music.Entity.Album", b =>
                {
                    b.Navigation("musics");
                });

            modelBuilder.Entity("Music.Entity.Musicc", b =>
                {
                    b.Navigation("song");
                });

            modelBuilder.Entity("Music.Entity.Singer", b =>
                {
                    b.Navigation("albums");
                });

            modelBuilder.Entity("Music.Entity.SongTable", b =>
                {
                    b.Navigation("songs");
                });

            modelBuilder.Entity("Music.Entity.User", b =>
                {
                    b.Navigation("songTables");
                });
#pragma warning restore 612, 618
        }
    }
}
