// <auto-generated />
using System;
using DbCource.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbCource.EntityFramework.Migrations
{
    [DbContext(typeof(DbCourceContext))]
    [Migration("20241230180230_init1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DbCource.Entity.Contract", b =>
                {
                    b.Property<Guid>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InboundID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProductID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupplierID")
                        .HasColumnType("TEXT");

                    b.HasKey("ContractID");

                    b.HasIndex("ContractID")
                        .IsUnique();

                    b.HasIndex("InboundID")
                        .IsUnique();

                    b.HasIndex("ProductID");

                    b.HasIndex("SupplierID");

                    b.ToTable("contracts");
                });

            modelBuilder.Entity("DbCource.Entity.Inbound", b =>
                {
                    b.Property<Guid>("InboundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InboundTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InboundID");

                    b.HasIndex("InboundID")
                        .IsUnique();

                    b.ToTable("inbounds");
                });

            modelBuilder.Entity("DbCource.Entity.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceFluctationRange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductStabilityRate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupplierID")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.HasIndex("SupplierID");

                    b.ToTable("products");
                });

            modelBuilder.Entity("DbCource.Entity.Supplier", b =>
                {
                    b.Property<Guid>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuaAuthority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QuaEndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierID");

                    b.HasIndex("SupplierID")
                        .IsUnique();

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("DbCource.Entity.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("DbCource.Entity.Contract", b =>
                {
                    b.HasOne("DbCource.Entity.Inbound", "Inbound")
                        .WithOne("Contracts")
                        .HasForeignKey("DbCource.Entity.Contract", "InboundID");

                    b.HasOne("DbCource.Entity.Product", "Product")
                        .WithMany("Contracts")
                        .HasForeignKey("ProductID");

                    b.HasOne("DbCource.Entity.Supplier", "Supplier")
                        .WithMany("Contracts")
                        .HasForeignKey("SupplierID");

                    b.Navigation("Inbound");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DbCource.Entity.Product", b =>
                {
                    b.HasOne("DbCource.Entity.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierID");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DbCource.Entity.Inbound", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("DbCource.Entity.Product", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("DbCource.Entity.Supplier", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
